server:
  port: 8081
spring:
  application:
    name: jrtp701miniproject_train_enquiry
  config:
    activate:
      on_profile: h2
  datasource:
    url: jdbc:h2:mem:trainsdb
    username: gopesh
    password: gopesh
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
